name: PM Audits
on: [pull_request]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    name: Lighthouse
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Wait for Netlify
        uses: kamranayub/wait-for-netlify-action@2.0.0
        id: netflify
        with:
          site_name: hugo-template
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      - name: Run Lighthouse audit
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ steps.netflify.outputs.url }}
            ${{ steps.netflify.outputs.url }}/articles/
            ${{ steps.netflify.outputs.url }}/articles/dinozavri-so-nazaj/
          # You cant use budget and assertions from lighthouserc
          # budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: ./.lighthouserc.yml

  links:
    runs-on: ubuntu-latest
    name: Links
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Wait for Netlify
        uses: kamranayub/wait-for-netlify-action@2.0.0
        id: netflify
        with:
          site_name: hugo-template
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      - run: npm install hyperlink tap-dot
      - run: node_modules/.bin/hyperlink ${{ steps.netflify.outputs.url }} -r | tee site.tap | node_modules/.bin/tap-dot

  a11y:
    runs-on: ubuntu-latest
    name: Accessibility
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Wait for Netlify
        uses: kamranayub/wait-for-netlify-action@2.0.0
        id: netflify
        with:
          site_name: "hugo-template"
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      - run: npm install pa11y
      - run: node_modules/.bin/pa11y ${{ steps.netflify.outputs.url }}
