name: PM Performance Test
on: [pull_request]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    name: Lighthouse Audit

    steps:
      - uses: actions/checkout@v2
      - name: Wait for Netlify
        uses: kamranayub/wait-for-netlify-action@2.0.0
        id: netflify
        with:
          site_name: "hugo-template"
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ steps.netflify.outputs.url }}
          budgetPath: ./budget.json
          uploadArtifacts: true
